CREATE DATABASE IF NOT EXISTS `api_udemy` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

CREATE TABLE IF NOT EXISTS `api_udemy`.`person` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(100) NOT NULL,
  `firstName` VARCHAR(80) NOT NULL,
  `lastName` VARCHAR(80) NOT NULL,
  `gender` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`));